version: "3"
services:
  node_dev:
    build: .
    container_name: node-docker
    restart: always
    ports:
      - 80:3000
      - 8080:8080
    volumes:
      - ./:/home/app
      #- /media/linus/WEBARCHIV:/home/app/storage
      #- /media/hadoken/speicher:/home/app/storage
      #- /media/linus/70DE-6DBF:/home/app/storage
      # windowsmount all other volumes need to be disabled
      #- E:\\:/home/app/storage
    
    #stdin_open: true
    #tty: true
    