version: "3"
services:
  node_dev:
    build: .
    container_name: node-docker
    restart: always
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      #- /home/$USER/run:/home/app/storage
      #- ./:/home/app
      - /media/videoarchiv:/home/app/storage #mount local HDD to Server
      # example of windowsmount
      #- E:\\:/home/app/storage
    
    #stdin_open: true
    #tty: true
    