version: "3"
services:
  node_dev:
    build: .
    container_name: node-docker
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ./:/home/app
      - /media/linus/CORSAIR:/home/app/storage
    
    stdin_open: true
    tty: true